#ifndef CHOOMI_COMMON_H
#define CHOOMI_COMMON_H

// 项目基础定义
#define CHOOMI_TAG "CHOOMI"
#define WDT_TIMEOUT 30
#define MAX_RECORDING_TIME_MS 30000
#define HEARTBEAT_INTERVAL_MS 30000

// 硬件配置定义
#define CPU_FREQ_MHZ 160
#define FREERTOS_TICK_HZ 1000

// 系统状态定义
typedef enum {
    CHOOMI_STATE_INIT,
    CHOOMI_STATE_READY,
    CHOOMI_STATE_RECORDING,
    CHOOMI_STATE_PLAYING,
    CHOOMI_STATE_NETWORK_CONNECTING,
    CHOOMI_STATE_ERROR
} choomi_state_t;

// 错误代码定义
typedef enum {
    CHOOMI_OK = 0,
    CHOOMI_ERR_INIT_FAILED,
    CHOOMI_ERR_HARDWARE_FAILED,
    CHOOMI_ERR_NETWORK_FAILED,
    CHOOMI_ERR_AUDIO_FAILED,
    CHOOMI_ERR_DISPLAY_FAILED
} choomi_err_t;

#endif // CHOOMI_COMMON_H